/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-dim": "#00deec",
        "on-primary": "#005d63",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-fixed-dim": "#c1d0e6",
        "secondary-fixed": "#f1c1ff",
        "on-secondary-fixed": "#580079",
        "surface-variant": "#192540",
        "error-container": "#9f0519",
        "on-secondary-container": "#fff5fc",
        "secondary-dim": "#bb00fc",
        "primary-container": "#00eefc",
        "error-dim": "#d7383b",
        "on-tertiary-container": "#414f62",
        "surface-container-high": "#141f38",
        "on-primary-container": "#005359",
        "tertiary-container": "#cfdef5",
        "surface-bright": "#1f2b49",
        "surface-dim": "#060e20",
        "primary-fixed": "#00eefc",
        "on-secondary-fixed-variant": "#8400b3",
        "on-surface-variant": "#a3aac4",
        "on-tertiary": "#49586b",
        "on-error": "#490006",
        "surface": "#060e20",
        "tertiary-fixed": "#cfdef5",
        "surface-container": "#0f1930",
        "secondary-container": "#9900cf",
        "on-tertiary-fixed": "#2e3d4e",
        "surface-container-lowest": "#000000",
        "on-primary-fixed": "#003f43",
        "surface-container-low": "#091328",
        "on-background": "#dee5ff",
        "tertiary-dim": "#c1d0e6",
        "outline-variant": "#40485d",
        "secondary-fixed-dim": "#eaaeff",
        "tertiary": "#e0ecff",
        "on-error-container": "#ffa8a3",
        "background": "#060e20",
        "surface-container-highest": "#192540",
        "inverse-surface": "#faf8ff",
        "inverse-primary": "#006a71",
        "error": "#ff716c",
        "primary-fixed-dim": "#00deec",
        "on-tertiary-fixed-variant": "#4a596c",
        "outline": "#6d758c",
        "secondary": "#d674ff",
        "on-surface": "#dee5ff",
        "inverse-on-surface": "#4d556b",
        "surface-tint": "#8ff5ff",
        "on-secondary": "#390050",
        "primary": "#8ff5ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
