-- Schema Spectra — H2 (CREATE TABLE IF NOT EXISTS → idempotent)
-- Ce fichier est la source de vérité du schéma.
-- Modifier une entité JPA sans mettre à jour ce fichier provoque une erreur
-- au démarrage (ddl-auto: validate) — c'est voulu.
-- En développement local, utiliser le profil "dev" (ddl-auto: update) puis
-- reporter les changements ici avant de pousser.

CREATE TABLE IF NOT EXISTS ingested_files (
    sha256           VARCHAR(255)             NOT NULL,
    file_name        VARCHAR(255),
    format           VARCHAR(255),
    ingested_at      TIMESTAMP WITH TIME ZONE,
    chunks_created   INTEGER                  NOT NULL DEFAULT 0,
    lifecycle        VARCHAR(50),
    version          INTEGER                  NOT NULL DEFAULT 1,
    tags             TEXT,
    quality_score    DOUBLE PRECISION,
    collection_name  VARCHAR(255),
    PRIMARY KEY (sha256)
);

CREATE TABLE IF NOT EXISTS ingestion_tasks (
    task_id              VARCHAR(255)             NOT NULL,
    status               VARCHAR(50),
    files                TEXT,
    chunks_created       INTEGER                  NOT NULL DEFAULT 0,
    error                TEXT,
    created_at           TIMESTAMP WITH TIME ZONE,
    completed_at         TIMESTAMP WITH TIME ZONE,
    parser_used          VARCHAR(255),
    layout_aware_chunks  INTEGER                  NOT NULL DEFAULT 0,
    PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS generation_tasks (
    task_id          VARCHAR(255) NOT NULL,
    status           VARCHAR(50),
    pairs_generated  INTEGER      NOT NULL DEFAULT 0,
    chunks_processed INTEGER      NOT NULL DEFAULT 0,
    total_chunks     INTEGER      NOT NULL DEFAULT 0,
    error            TEXT,
    PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS article_comments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sha256  VARCHAR(255)             NOT NULL,
    content          TEXT                     NOT NULL,
    author           VARCHAR(255),
    comment_type     VARCHAR(50)              NOT NULL,
    rating           VARCHAR(50)              NOT NULL,
    rag_context      TEXT,
    focus            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ged_audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sha256  VARCHAR(255)             NOT NULL,
    action           VARCHAR(50)              NOT NULL,
    actor            VARCHAR(255),
    timestamp        TIMESTAMP WITH TIME ZONE NOT NULL,
    details          TEXT
);

CREATE TABLE IF NOT EXISTS document_model_links (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sha256  VARCHAR(255) NOT NULL,
    model_name       VARCHAR(255) NOT NULL,
    link_type        VARCHAR(50)  NOT NULL,
    linked_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_doc_model_link UNIQUE (document_sha256, model_name, link_type)
);

CREATE TABLE IF NOT EXISTS fine_tuning_jobs (
    job_id           VARCHAR(255) NOT NULL,
    status           VARCHAR(50),
    model_name       VARCHAR(255),
    base_model       VARCHAR(255),
    parameters       TEXT,
    dataset_size     INTEGER      NOT NULL DEFAULT 0,
    current_step     VARCHAR(255),
    current_epoch    INTEGER,
    total_epochs     INTEGER,
    loss             DOUBLE PRECISION,
    output_path      VARCHAR(255),
    report_path      VARCHAR(255),
    error            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE,
    completed_at     TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (job_id)
);
