-- Schema Spectra — H2 (CREATE TABLE IF NOT EXISTS → idempotent)
-- Ce fichier est la source de vérité du schéma.
-- Modifier une entité JPA sans mettre à jour ce fichier provoque une erreur
-- au démarrage (ddl-auto: validate) — c'est voulu.
-- En développement local, utiliser le profil "dev" (ddl-auto: update) puis
-- reporter les changements ici avant de pousser.

CREATE TABLE IF NOT EXISTS ingested_files (
    sha256           VARCHAR(255)             NOT NULL,
    file_name        VARCHAR(255),
    format           VARCHAR(255),
    ingested_at      TIMESTAMP WITH TIME ZONE,
    chunks_created   INTEGER                  NOT NULL DEFAULT 0,
    lifecycle        VARCHAR(50),
    version          INTEGER                  NOT NULL DEFAULT 1,
    tags             TEXT,
    quality_score    DOUBLE PRECISION,
    collection_name  VARCHAR(255),
    archived_at      TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (sha256)
);

-- Migration : bases créées avant l'ajout de archived_at (idempotent sous H2)
ALTER TABLE ingested_files ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS ingestion_tasks (
    task_id              VARCHAR(255)             NOT NULL,
    status               VARCHAR(50),
    files                TEXT,
    chunks_created       INTEGER                  NOT NULL DEFAULT 0,
    chunks_expected      INTEGER                  NOT NULL DEFAULT 0,
    error                TEXT,
    created_at           TIMESTAMP WITH TIME ZONE,
    completed_at         TIMESTAMP WITH TIME ZONE,
    parser_used          VARCHAR(255),
    layout_aware_chunks  INTEGER                  NOT NULL DEFAULT 0,
    file_errors          TEXT,
    PRIMARY KEY (task_id)
);

-- Migration : bases créées avant l'ajout de chunks_expected (idempotent sous H2)
ALTER TABLE ingestion_tasks ADD COLUMN IF NOT EXISTS chunks_expected INTEGER NOT NULL DEFAULT 0;
-- Migration : bases créées avant l'ajout des erreurs par fichier (idempotent sous H2)
ALTER TABLE ingestion_tasks ADD COLUMN IF NOT EXISTS file_errors TEXT;

CREATE TABLE IF NOT EXISTS generation_tasks (
    task_id          VARCHAR(255) NOT NULL,
    status           VARCHAR(50),
    pairs_generated  INTEGER      NOT NULL DEFAULT 0,
    chunks_processed INTEGER      NOT NULL DEFAULT 0,
    total_chunks     INTEGER      NOT NULL DEFAULT 0,
    error            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (task_id)
);

-- Migration : bases créées avant l'ajout de created_at (idempotent sous H2)
ALTER TABLE generation_tasks ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS article_comments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sha256  VARCHAR(255)             NOT NULL,
    content          TEXT                     NOT NULL,
    author           VARCHAR(255),
    comment_type     VARCHAR(50)              NOT NULL,
    rating           VARCHAR(50)              NOT NULL,
    rag_context      TEXT,
    focus            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ged_audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sha256  VARCHAR(255)             NOT NULL,
    action           VARCHAR(50)              NOT NULL,
    actor            VARCHAR(255),
    timestamp        TIMESTAMP WITH TIME ZONE NOT NULL,
    details          TEXT
);

CREATE TABLE IF NOT EXISTS document_model_links (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_sha256  VARCHAR(255) NOT NULL,
    model_name       VARCHAR(255) NOT NULL,
    link_type        VARCHAR(50)  NOT NULL,
    linked_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_doc_model_link UNIQUE (document_sha256, model_name, link_type)
);

CREATE TABLE IF NOT EXISTS fine_tuning_jobs (
    job_id           VARCHAR(255) NOT NULL,
    status           VARCHAR(50),
    model_name       VARCHAR(255),
    base_model       VARCHAR(255),
    parameters       TEXT,
    dataset_size     INTEGER      NOT NULL DEFAULT 0,
    current_step     VARCHAR(255),
    current_epoch    INTEGER,
    total_epochs     INTEGER,
    loss             DOUBLE PRECISION,
    output_path      VARCHAR(255),
    report_path      VARCHAR(255),
    error            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE,
    completed_at     TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (job_id)
);

-- Suivi persistant des installations Model Hub (llmfit download) : survit au redémarrage
-- de l'API pour un historique fiable et la réconciliation des téléchargements interrompus.
CREATE TABLE IF NOT EXISTS installation_jobs (
    job_id           VARCHAR(255) NOT NULL,
    status           VARCHAR(50),
    model_name       VARCHAR(255),
    quant            VARCHAR(64),
    auto_activate    BOOLEAN      NOT NULL DEFAULT FALSE,
    progress         INTEGER      NOT NULL DEFAULT 0,
    current_step     VARCHAR(255),
    output_path      VARCHAR(255),
    previous_active_model VARCHAR(255),
    error            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE,
    completed_at     TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (job_id)
);

-- Migration : bases créées avant l'ajout du modèle actif précédent (idempotent sous H2).
ALTER TABLE installation_jobs ADD COLUMN IF NOT EXISTS previous_active_model VARCHAR(255);

-- Ingestion streaming Kafka : état par identité métier (données vivantes).
CREATE TABLE IF NOT EXISTS kafka_stream_source (
    source_key       VARCHAR(512) NOT NULL,
    collection       VARCHAR(255),
    content_hash     VARCHAR(64),
    chunk_count      INTEGER      NOT NULL DEFAULT 0,
    version          BIGINT       NOT NULL DEFAULT 0,
    first_seen_at    TIMESTAMP WITH TIME ZONE,
    last_updated_at  TIMESTAMP WITH TIME ZONE,
    last_offset_ref  VARCHAR(512),
    PRIMARY KEY (source_key)
);

-- Index de performance (ddl-auto: validate ne crée pas les index déclarés via @Index ;
-- ils doivent donc être créés ici, source de vérité du schéma). Idempotents.
CREATE INDEX IF NOT EXISTS idx_kafka_stream_updated_at    ON kafka_stream_source(last_updated_at);
CREATE INDEX IF NOT EXISTS idx_kafka_stream_collection    ON kafka_stream_source(collection);
CREATE INDEX IF NOT EXISTS idx_ingested_files_lifecycle   ON ingested_files(lifecycle);
CREATE INDEX IF NOT EXISTS idx_ingested_files_ingested_at ON ingested_files(ingested_at);
CREATE INDEX IF NOT EXISTS idx_ingested_files_collection  ON ingested_files(collection_name);
CREATE INDEX IF NOT EXISTS idx_ged_audit_sha256           ON ged_audit_log(document_sha256);
CREATE INDEX IF NOT EXISTS idx_ged_audit_timestamp        ON ged_audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_doc_model_sha256           ON document_model_links(document_sha256);
CREATE INDEX IF NOT EXISTS idx_doc_model_name             ON document_model_links(model_name);
