name: Links Checker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 0 * * 1" # Run weekly on Mondays

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Link Checker (Lychee)
        uses: lycheeverse/lychee-action@v2.0.1
        with:
          args: --exclude-mail --verbose --no-progress './**/*.md' './**/*.html'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Always upload the report if the action fails
      - name: Upload Lychee report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
